application: jennifer-garner-711
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

pagespeed:
  enabled_rewriters:
  - MinifyCss
  - ProxyCSS
  - ProxyImages
  - ProxyJS
  - ConvertMetaTags
  - InlineCSS
  - InlineImages
  - InlinePreviewImages
  - CollapseWhitespace
  - CombineHeads
  - ElideAttributes
  - RemoveComments
  - RemoveQuotes
  - LeftTrimUrls
  - CombineCss
  - MoveCssToHead
  - WebpOptimization
  - ImageConvertToJpeg
  - ImageRecompressJpeg
  - ImageProgressiveJpeg
  - ImageRecompressPng
  - ImageStripMetadata
  - ImageStripColorProfile
  - ImageResize
  - LazyloadImages
  - ImageAddDimensions
